"""Pydantic schemas for vision-based civic image analysis responses."""

from typing import List, Optional
from pydantic import BaseModel, Field
from ..models.complaint import ComplaintCategoryEnum, ComplaintPriorityEnum


class BoundingBox(BaseModel):
    """Approximate bounding box for a detected defect region (normalized 0.0–1.0)."""
    x: float = Field(..., ge=0.0, le=1.0, description="Left edge (normalized)")
    y: float = Field(..., ge=0.0, le=1.0, description="Top edge (normalized)")
    width: float = Field(..., ge=0.0, le=1.0, description="Width (normalized)")
    height: float = Field(..., ge=0.0, le=1.0, description="Height (normalized)")


class CivicDefectDetection(BaseModel):
    """A single detected civic defect within the submitted photograph."""
    label: str = Field(..., description="Human-readable defect description from AI")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Detection confidence (0.0–1.0)")
    severity: str = Field(..., description="Severity level: LOW | MEDIUM | HIGH | CRITICAL")
    bounding_box: Optional[BoundingBox] = Field(
        None,
        description="Approximate region of defect in image. None if model does not provide spatial location."
    )


class VisionAnalysisResponse(BaseModel):
    """
    Response from the CivicFix vision AI analysis endpoint.

    All fields reflect actual AI model output — nothing is hardcoded or fabricated.
    If the AI cannot confidently determine a field, it is returned as None or 'unknown'.
    """

    # Primary detection result
    primary_issue: Optional[str] = Field(
        None,
        description="Primary civic issue identified in the image. None if no civic issue detected."
    )
    is_civic_issue: bool = Field(
        ...,
        description="True if the image contains an identifiable civic infrastructure problem."
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description=(
            "AI model confidence in the primary issue identification (0.0–1.0). "
            "Distinct from severity — a minor pothole can have high confidence."
        )
    )
    severity: str = Field(
        ...,
        description=(
            "Issue severity: LOW | MEDIUM | HIGH | CRITICAL. "
            "Determined by the AI based on: immediate hazard to public safety, "
            "extent of infrastructure damage, urgency of repair needed, "
            "and potential for escalation. Independent of detection confidence."
        )
    )

    # Category suggestion
    suggested_category: Optional[ComplaintCategoryEnum] = Field(
        None,
        description="Suggested CivicFix complaint category based on visual analysis. None if uncertain."
    )
    suggested_department: Optional[str] = Field(
        None,
        description="Suggested responsible municipal department. None if uncertain."
    )

    # All detections (multi-defect support)
    detections: List[CivicDefectDetection] = Field(
        default_factory=list,
        description="All civic defects detected in the image, ordered by confidence descending."
    )

    # AI reasoning
    reasoning: str = Field(
        ...,
        description="AI's concise explanation of what it observed and why it made its determination."
    )

    # Location (passed through from client — never generated by AI)
    latitude: Optional[float] = Field(
        None,
        ge=-90.0,
        le=90.0,
        description="Location latitude. Sourced from device geolocation or user map pin — never invented by AI."
    )
    longitude: Optional[float] = Field(
        None,
        ge=-180.0,
        le=180.0,
        description="Location longitude. Sourced from device geolocation or user map pin — never invented by AI."
    )

    # Model metadata
    vision_model: str = Field(
        ...,
        description="The exact vision model identifier used for this analysis."
    )
    vision_provider: str = Field(
        ...,
        description="The AI provider used (e.g. 'openai', 'mock')."
    )
    analysis_available: bool = Field(
        ...,
        description=(
            "True if a real vision model processed the image. "
            "False if no vision credentials are configured (mock path)."
        )
    )
